name: my test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: test-org-javihernandez/private-repo
        path: private-repo
        token: ${{ secrets.OVAL_PROCESSOR_TOKEN }}
